### ISSUE TITLE
Tired of cheaters?

### ISSUE THREAD

**Issue by joedicastro** [igrigorik/vimgolf#120]
I'm tired of cheaters, there are many people who only gets their rank by copying, you know, they submit a challenge based in the best they can see at open in the site, then they scaled positions doing the same over and over again. Well I think so! Sure they are not all the people, but I think there's too much of this.

And I think that the public humiliation as a solution for this is not working at all!

There's a suggestion to get ride of all of this cheating all over the site.
This is the idea:
- At first, only the worst attempt is displayed, even if you are logged in.
- If you submit a challenge, only the scores worse than yours will be visible.   Of course, you can try again all the times you want.
- When your run out of new ideas for a better result or you're tired to try,  then you resign (adding this as a new option in the command line menu)
- Then you can see all the rest of the attempts in the site, and learn from them a lot, but  you can't submit a new attempt again.

What you think about this?

**Comment by ArendPeter** [comment]
I'm just starting with Vimgolf and I think it's a good learning tool. I like the idea of having a leader board since it gamifies the experience and it gives me a good idea of how my solution stacks up.

After coming up with my own, I also like copying other solutions in order to better understand them. and also so I can see even better solutions. However I don't like it that doing this pulls me up in rank since it's not really my problem solving ability that got me there.

That said I like the idea of having a fixed ranking for my first submission then having a second ranking which represents my latest submission.

**Comment by tecfu** [comment]
I think a moderation system could be introduced to solve this problem.  Answers with a syntax identical to a pre-existing same score response could be flagged and hidden from the leaderboard, but the person who answered the question would still retain their viewing rights to other high score answers. 

Also, I think the author/maintainer should offer to reveal all the "hidden" answers for a fee. This would create an incentive to better maintain and develop the product...which seems absent now.
