### ISSUE TITLE
Regex only mode

### ISSUE THREAD

**Issue by marianomacchi** [igrigorik/vimgolf#153]
I've recently discovered vimgolf and I have to say it has taught me a _lot_ of shortcuts, tricks and obscure commands in a short amount of time. More so than just reading a book. Plus, is really fun, so thanks for implementing it :)

But given the nature of the game (fewest keystrokes wins), I very rarely see regex solutions in the challenges, since they usually aren't "as optimal", for the game's objective, as movement hacks and macros.

This is unfortunate, since regex sometimes are really elegant and could be more useful in a real life scenario than custom hacks that exploit the challenge's specific line dispotition and chars.

Some of the most neat solutions I've come across were regex buried amid dozens of macros, I'd love to see more and "regex only" challenges, if feasible, could help with that.

**Comment by urticadioica** [comment]
If regex isn't winning, that should tell you something. It means maybe it wasn't the right tool for the job. It might be the right tool for some other job, but not this one.

If you want more regex at the top of leaderboards, what you need are different challenges, where it actually wins. If there's something in particular you want to see, I'll try to help. I can recommend challenges, or help work on new ones.

**Comment by MarianoMacchi** [comment]
Indeed, you're right, it's a lot easier just to make challenges that are easier to complete with a regexp. And I've seen there are some of those. It's just that the majority of challenges seem to be more fit to normal editing because they consists of small snippets of text and so is easier to see some patterns or movements that could be exploited than, say, in the case of a file of hundred of lines of which you little about (e.g. that you need to copy the text between some tags).

I'd just like to see what kind of obscure solutions people can come up with when regexp are the best approach. An example could be how to handle the conversion of an xml with no evenly distributed lines to plain text. New or old challenges of this kind you'd really be interesting.

**Comment by urticadioica** [comment]
[Get rid of html tags](https://www.vimgolf.com/challenges/4d1a7a05b8cb3409320001b4) explored tag removal, which is sort of what you're asking about. Challenge is a bit buggy, but the result is amusing... macros win again.

I can tell you the challenges with the most complex regexes so far. The recent [Conway sequence](https://www.vimgolf.com/challenges/54f8cc2718a13f0a630041e5) is somewhat interesting, though no one seems to want to play it. Better solutions are possible. [Here, piggy, piggy...](https://www.vimgolf.com/challenges/4d2513c10947c63e2600019f) implements pig latin, and is fairly well-established. That should give you some idea what kind of complexity it takes to force a back-reference.

Are you aware of [Regex Golf](https://regex.alf.nu/)? It hasn't managed to draw me in the same way Vimgolf did, but it's a neat idea. That sort of challenge is certainly possible in Vimgolf too.

**Comment by MarianoMacchi** [comment]
Thanks, I'll check these challenges.
Once I get to know vim's regexp in more detail I'll try to come up with ex related challenges to submit.
