### ISSUE TITLE
Not working with neovim

### ISSUE THREAD

**Issue by GCorbel** [igrigorik/vimgolf#162]
Hi,

I'm using neovim and, when I try to launch vimgolf, I have an error option because `--nofork` is not an option.

**Comment by urticadioica** [comment]
I investigated the options, and it looks like using `set guioptions+=f` in the vimrc could be an alternative. Neovim got rid of that too (according to its help files), but it should ignore the unknown flags. It should really ignore a historical command line option as well, instead of refusing to start, but I guess that's not in line with their design philosophy.

I think there are some differences in what solutions work in a few cases with Neovim. Seems like they got rid of ex mode, for example. But Vim itself changes from version to version, so I wouldn't want to drop support if we can help it.

**Comment by GCorbel** [comment]
I have another PC with vim properly installed and it works. I guess I have to install vim and say to vimgolf to work with it.

Thanks!

**Comment by letientai299** [comment]
I get the same issues today, posted here in case other people need it.
Because I don't want to replace neovim with the original vim, my solution is open the file:
```
vim +113 /var/lib/gems/2.3.0/gems/vimgolf-0.4.8/lib/vimgolf/cli.rb
```
and remove `--nofork` option.
After that, vimgolf and neovim work fine.

**Comment by majamin** [comment]
To extend the answer by @letientai299 : use `gem which vimgolf` to find the location of the gem on your system. This should open it where ever it exists:

`vim +112 $(gem which vimgolf | sed 's/vimgolf.rb/vimgolf\/cli.rb/g')`
