### ISSUE TITLE
Investigate new data model

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/vimgolf#174]
Discussion in https://github.com/igrigorik/vimgolf/issues/171.

- [ ] Identify queries for key pages: https://github.com/igrigorik/vimgolf/issues/171#issuecomment-269573643
- [ ] Build a test dataset / benchmark current data to identify bottlenecks
- [ ] Sketch out new data model proposals
  - Alternative data storage models, how we're going to query, etc. 
- [ ] Implement new data model
   - [ ] Re-enable user pages and leaderboard

Note: before we rush into "use X technology", let's understand the requirements and sketch out some paper solutions for how we're going to access the data.

**Comment by stevecrozz** [comment]
@igrigorik is the production database something that can be dumped and shared here? or at least dumped, scrubbed, and shared? Nothing beats the real thing for a test dataset, right?

**Comment by aaooki** [comment]
What do you think about writing a scrip to generate custom seed files with large data? We can then find where the bottlenecks are.

**Comment by igrigorik** [comment]
@stevecrozz yeah, I can do that. The challenges are fine, but I'd need to scrub the user data. That said, I like @aaooki's suggestion: it gives us flexibility to scale up the dataset to any arbitrary size.

**Comment by hexgnu** [comment]
I would love to help out here since I spend most of my days optimizing databases and I love vimgolf.

Also I would really stress not focusing on migrating to postgres unless there is a huge reason to... While I wouldn't pick mongo for vimgolf it is a perfectly fine database that can be worked with. If memory serves me right we can do some optimizations to make things operate quite fast.

Also @igrigorik what version of mongo is vimgolf running? We might be able to take advantage of some new features they've been working on.

**Comment by stevecrozz** [comment]
Not sure if anyone would find this helpful, but if we do stick with Mongo, I recorded my experience and approach to optimizing another open source Rails + Mongo app last year: https://lithostech.com/tags/errbit/

**Comment by hexgnu** [comment]
Something that seems loosely related to this (since it was the impetus that led to this issue): should there be a separate task for performance related optimizations?

While I'm a big fan of optimizing the queries, should we also try to add some caching strategy? When I looked at the code it didn't seem like there was a ton around caching.

**Comment by igrigorik** [comment]
@hexgnu 2.6.5, but we can upgrade to 3.x. It's a managed DB by compose(.io).

And yes, we should benchmark and identify where the problems are first, before we talk about switching databases / caching / etc.

**Comment by hexgnu** [comment]
@igrigorik if you could get me some stats I could come up with a benchmark.

* How many users are there?
* How many challenges are there?
* What is the max number of entries for a challenge?
* What is the max number of comments for an entry?

From there we can build a benchmark that steps up to the maximum and see what the asymptotic performance looks like. Also maybe it's a smart idea to see what 10x these max numbers are.

I feel personally that attempting to get a production dump (that protects users information) is less useful than creating a seed script.

**Comment by igrigorik** [comment]
Ballpark figures, with save buffer on top of existing metrics:

> How many users are there? - 50K.
> How many challenges are there? - 3K.
> What is the max number of entries for a challenge? - tens of thousands.
> What is the max number of comments for an entry? - hundreds.

**Comment by hexgnu** [comment]
So I made a quick seed script which is helpful in creating a bunch of data. though it takes forever to actually run :smile:..

While I work on making it more useful... some things I've noticed.

It appears that there are a lot of cases where things are being sorted in ruby instead of utilizing mongo. For instance on the front page it loads all the challenges, and sorts them according to an interestingness score.

I think we might get a lot of benefit out of doing a few things, adding things like scores or entry counts to the underlying model and ordering using mongo instead of ruby.

Also the app becomes pretty slow when loading up many thousands of challenges. I know it was said elsewhere but if we are able to move all the ordering into mongo queries instead of ruby adding kaminari would be pretty trivial.

I'll see if I can hack on this some more over the next days but as of yet I don't have anything to really show or contribute.

**Comment by igrigorik** [comment]
> It appears that there are a lot of cases where things are being sorted in ruby instead of utilizing mongo. For instance on the front page it loads all the challenges, and sorts them according to an interestingness score.

Right, this is also a side effect of the original assumption that we want to list *all* challenges on the homepage. In reality, this is actually not as expensive as it may seem, but I do think that some pagination may not be a bad idea. 

> I think we might get a lot of benefit out of doing a few things, adding things like scores or entry counts to the underlying model and ordering using mongo instead of ruby.

For the challenge page, the parsing of the solutions—to show human readable keystrokes—is actually pretty expensive (on the order of ~10~20ms per entry). Right now we fetch all of them and show most of them, which is pretty expensive. Once again, some smarter pagination would go a long way. I'd love to see an infinite scroll solution for this one in particular.

---

Today, the most expensive operations, by far, are the user profile pages... which I recently had to disable. The problem there is that we have to invert the dataset, which is keyed by challenges, and find each users' top entry, compute their rank, and then repeat for every challenge.

---

All that said, I think we can start with small steps:
- Add sorting in DB + infinite scroll on the page
- Add sorting in DB + pagination on main page to see the challenges
- Then figure out how to rebuild user profile + leaderboard

**Comment by benoittgt** [comment]
@hexgnu do you think you can share this seed script? 

I can work on a [bench similar to discourse](https://github.com/discourse/discourse/blob/master/script/bench.rb) or a simpler using [derailed](https://github.com/schneems/derailed_benchmarks). If we are good with test coverage (super job @zoso10 🎉).

**Comment by hexgnu** [comment]
@benoittgt I don't since I cleaned my computer a while back :-/ it's probably not too difficult to make one again though

**Comment by h43z** [comment]
@hexgnu any chance you have a seed script or db dump. would love to hack on vimgolf :)

**Comment by hexgnu** [comment]
@h43z I don't have one since I cleaned my computer.

**Comment by igrigorik** [comment]
Resolving. Should be addressed by https://github.com/igrigorik/vimgolf/pull/248.
