### ISSUE TITLE
Slow javascript

### ISSUE THREAD

**Issue by urticadioica** [igrigorik/vimgolf#192]
Since at least several months ago, some piece of javascript on vimgolf.com has been running slow on large challenge pages. I think I've found the problem: a [call to `.button()` in application.js](https://github.com/igrigorik/vimgolf/blob/master/public/javascripts/application.js#L3). Removing it on a local copy removes the issue.

[This link](https://bugs.jqueryui.com/ticket/5454) suggests that initializing a button in jQuery involves an expensive DOM search every time it's triggered, so it causes problems on large pages.

Severity: On the largest pages, this problem causes up to a 30 second delay after `$(document).ready` triggers, after which I can't scroll. (That's on my modern-but-bargain-cheap laptop, running Firefox.) I get up to 3 "Stop script" dialogs during that time. For users who can't see all the solutions yet, it won't be quite so bad, but after they climb the leaderboard...

**Comment by Hettomei** [comment]
We can see it in chrome devtool ! so much time/cpu spent to have a "good looking" button :)

I let a comment here to remember to delete "application.js" that do nothing than adding some css on 2 buttons.

My smartphone crashed because of this. So I think it is a step to "make it more mobile friendly"

**Comment by igrigorik** [comment]
I'm all for removing those libraries in favor of vanilla CSS and JS markup. :)
