### ISSUE TITLE
More authentication options, unnecessary restrictions.

### ISSUE THREAD

**Issue by Granitosaurus** [igrigorik/vimgolf#205]
Needless to say having only 1 authentication option that is based on some 3rd party website is a bad idea - would be really nice to have more authentication options. 

Why do I need to authenticate to see more answers anyway? This practise is very restricting for no reason at all.

I'm pretty sure I'm not the only one that has no interest in making a twitter account.

**Comment by igrigorik** [comment]
> Why do I need to authenticate to see more answers anyway? This practise is very restricting for no reason at all.

You don't need to be authenticated to see more answers. You need to _submit_ an entry to see solutions with higher scores, which requires that you're authenticated. This decision is by design, to force you to learn through practice (and iteration), instead of simply looking up the top answer.

With respect to Twitter: it offers simple integration, avatars, and sharing. No plans to add more options as of yet.. I'm not against it, as long as it doesn't add undue complexity, but we need to solve other issues first.
