### ISSUE TITLE
What's to stop people copying and submitting solutions better than theirs until they reach the top?

### ISSUE THREAD

**Issue by tysonzero** [igrigorik/vimgolf#218]
Unless I am missing something anyone can copy their way to the top. IMO you should not get to see solutions better than yours, seems to me as though it hurts the legitimacy of the scoreboard.

**Comment by urticadioica** [comment]
There's nothing to stop you. The leaderboards, as a scoring system, are meaningless. The overwhelming majority of ties for first place are copies.

There are a lot of ways the system could be tweaked, but I absolutely want to allow people to see better solutions. Not just to learn from them, but because a lot of top solutions are too awesome to hide. You should definitely try for yourself before looking, but you're just not going to get a lot of the best solutions. They're too good. And without learning from others, the authors of those solutions would never have gotten good enough to make them.

If you want to compete:

* Beat 1st place. Probably not possible on most challenges, but I guarantee it's possible on some of them. I just don't know which ones (or I'd do it myself). I'll warn you though, this is very hard.
* Make hard challenges. On most of my own challenges, I design them as a puzzle. I'm trying to make the simplest, shortest challenge I can that will stump the community. Usually I post my own solution after 24 hours, but whatever. If I take still take 1st place, I win.
* Play on [Anarchy Golf](http://golf.shinh.org/). Most challenges over there have deadlines, and best score before the deadline is 1st place, but you can see all solutions and keep playing after that. Not a lot of vimgolfers though. Only active challenge right now is [rising number](http://golf.shinh.org/p.rb?rising+number), where I have 34. Most of these challenges are designed for legit programming languages, not text editors, so it can be difficult, but it's appealing in its own way.

**Comment by igrigorik** [comment]
Strong +1 to all @urticadioica's points. Closing, but feel free to reopen if there is more to explore here.
