### ISSUE TITLE
Copy & paste

### ISSUE THREAD

**Issue by juancolacelli** [igrigorik/vimgolf#222]
If you copy and paste, it works...

    dG"+pZZ

You can see it working here: http://vimgolf.com/challenges/596ba8373e3dd71412000004

**Comment by urticadioica** [comment]
I deleted the entry. This is the same as #170. Since there's no server-side verification, there are a large number of possible cheats. This particular cheat is a little more annoying, because someone figures it out every month or two. You can make a good argument for disabling clipboard support, though as I mentioned in the other report, that would remove a semi-legit strat where you copy text to a register using visual mode. If you want to make that argument, I don't mind at all. I don't have a strong opinion either way.

**Comment by juancolacelli** [comment]
Thanks for deleting the entry and I'm sorry if I annoyed you, I was just trying to help.
