### ISSUE TITLE
editing the tmp file externally allows for universal 2-score solutions

### ISSUE THREAD

**Issue by towc** [igrigorik/vimgolf#230]
# Story

I was trying to do play around with a challenge with my own vimrc, and I noticed that when I open a challenge (`vimgolf put 5a0c38cd2e62f404f000001b`), the tmp filename appears in the statusline:

```
"/tmp/vimgolf20180402-10830-1omjcb7.txt" 3L, 25C                                                     1,1           All
```

in this case.

I just opened another terminal, ran `vim /tmp/vimg<Tab>`, and it opened the file. I finished playing around, and decided to write to the file, to see what would happen.

I then got back to the first terminal, with the file opened through `vimgolf`, and wrote/quit with `ZZ`. Vimgolf said that the files matched, and my score was 2. I then hoped there would be some kind of filter in the backend for this, but nope, my answer was right there, at the top of the leaderboard

# steps to reproduce

1) open two terminals: T1, T2
2) T1: run `vimgolf put <arbitrary challenge id>`
3) T2: run `vim /tmp/vimg<tab>`
4) T2: modify file as required by challenge
5) T2: write the file in its current location (`:w`)
6) T1: from that vim instance, just type `ZZ` to write and quit
7) T1: press `x<Enter>` to upload your answer
8) go to `http://vimgolf.com/challenges/<arbitrary challenge id>` and see your answer at the top, with a score of 2

# suggested fix

There have been a couple cheats going around, mostly relying on the fact that vim is running on a client. It would be a pain to try to fix every scenario, with a proper instance of vim running. A more interesting perspective would be to have vim run on the browser through codemirror or similar (would still need backend verification, but would make a lot of the workarounds unusable), or sending the keystrokes to a server, and letting the server deal with checking and changing the text.

Naturally both of these would be slightly slower for the user, but I think they would encourage people to try vim out, even if not in its natural state.

# reality check

I realize the authors built this site for fun, so if they decide to delete this issue so that the info at least doesn't spread, I would be completely ok with that, and I'll also delete my 2 entries that use this trick

**Comment by igrigorik** [comment]
Thanks for the detailed report! 

You're spot on.. the "issue" here is that we trust the client. When the result is uploaded we do [the most basic sanity check](https://github.com/igrigorik/vimgolf/blob/master/app/controllers/entry_controller.rb#L16) and otherwise assume that's a valid solution. Not surprisingly, this opens up opportunity for cheating and we've seen more than a few folks (re)discover this over the years.

Our solution to date has been simple: turns out most folks fall in the same camp as you (the point is to learn Vim, so they self policy after they have some fun :), and in some cases we have one of the moderators remove the invalid solution. So far, this served us well enough.

That said, I really like your idea of vim in the browser! Back when I first built this, that was still a sketchy proposition, but I have a feeling that today that's imminently doable and would make the whole process even simpler and a lot more fun.. Hmm! :)

**Comment by igrigorik** [comment]
@Hettomei I'd *love* to see an experiment where we integrate that into VimGolf. :-)

That said, if that's something we want to explore, let's open a new design thread on it.
