### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by xaltsc** [igrigorik/vimgolf#267]
the latest release is 4 years old and so is the gem.

**Comment by filbranden** [comment]
Bump! Can we please have a new gem? I'm getting the `<fd-61>` thing happening often too...

**Comment by Hettomei** [comment]
@filbranden about the fd-61 problem you can try this workaround if you have docker : https://github.com/igrigorik/vimgolf/issues/268#issuecomment-648723503

**Comment by filbranden** [comment]
@Hettomei The `kramos/vimgolf` Docker image is quite inadequate since it ships Vim 7.4.488 which lacks some important features such as the [`g CTRL-A`](https://vimhelp.org/change.txt.html#v_g_CTRL-A) visual mode command. (Which, BTW, ought to be addressed...)

In any case, the "official" instructions to run it (the three liner at the top right corner) start with `gem install vimgolf`. (Even in cases where Docker is available, sometimes running locally is easier and more convenient, especially where Ruby is readily available.)

It looks like the `<fd-61>` issue was fixed by commit 3bf4116f786148bc49f23056a4fc363425d18cbb, back from 2017 (three and a half years ago.)

Looks like the Gem last release was [version 0.4.8](https://rubygems.org/gems/vimgolf/versions/0.4.8), back in 2015 (five and a half years ago.)

There were [15 commits](https://github.com/igrigorik/vimgolf/commits/master/lib/vimgolf) to `lib/vimgolf` since release v0.4.8.

So I think there are quite a few good reasons to release a new Gem...

Are there any drawbacks of doing so?

Otherwise, can we please get a new release? Pretty please? :-)

Thanks!
Filipe

**Comment by genebustam** [comment]
I agree with this.
