### ISSUE TITLE
See all entries by the same user for a specific challenge

### ISSUE THREAD

**Issue by filbranden** [igrigorik/vimgolf#271]
If a user posts for answers with 157, 156, 155 and finally 151 characters, the challenge page will only show the entry with 151 characters and not the other ones.

The other ones are counted in the total number of entries for that challenge and also on the user page you'd see the user submitted 4 answers.

Would it be possible to show all entries from a single user?

Perhaps if not by default, expose a button to display them all?

Example challenge:
http://www.vimgolf.com/challenges/5c1db460c5949f000990a2f1

 3 active golfers, 6 entries 
(4 are mine)

http://www.vimgolf.com/filbranden
For that particular challenge, shows...
Number of attempts: 4

I think my previous attempts (with 157, 156 and 155 characters) are quite interesting, so I wish they were available as well.

Thanks!

**Comment by TitouanT** [comment]
I agree, it could also be in the form of a timeline to see how people got to the shortest solution. Because sometime there is a back and forth between golfers battling for the 1st place :)
And also it would be nice to keep the comments made on previous solution, there are some pretty interesting discussions sometimes.

**Comment by Hettomei** [comment]
@titouanT maybe you already know it : every comment and every solution are stored. We just need to display it the right way.

If somebody can make a mock up of a clean view ?

I don't have any ideas, but I think theire is something to do with another issue that ask to group 'same entries' of different users.

**Comment by TitouanT** [comment]
@Hettomei I did not knew it but I suspected it, this is good news :)

- In the UI, a button that toggles between "best entry by player" (default) and "all entries of all players" could do the trick
- And the timeline thing could be a another button that toggles between "sort by length (smaller first)" (default) and "sort by date (older first)"
- The per user access could be on the user page, with a challenge id in the url as an optional parameter that would add all the entries in chronological order on the right side of the page (same place as leader-board on a challenge page).
- an alternative to the previous point could be a drop down under each "Played Challenges" to show the player submissions (this one might be better).

@filbranden are my propositions in line with your issue ? (I hope they are ^^)

I think that it would not require too much work since it's all just using what is already there to display entries.

For the grouping of identical entries, maybe just add a "first" label to entries never seen before.
Or add a third option to the first button that would be best "first" entry.

example:
```
Let's assume that two solution of the same length are equal (not true in real vimgolf)
player A, B, C, and D did in chronological order :
A1 -> 22 (first)
A2 -> 19 (first)

B1 -> 21 (first)
B2 -> 18 (first)

A3 -> 18

C1 -> 23 (first)
C2 -> 22
C3 -> 21
C4 -> 19
C5 -> 18

D1 -> 22

then "best by player" would be:
B2 -> 18 (first)
A3 -> 18
C5 -> 18
D1 -> 22

"best first by player" would be:
A2 -> 19 (first)
B2 -> 18 (first)
C1 -> 23 (first)
(player D Disappeared here)
```

**Comment by Hettomei** [comment]
@TitouanT 
Thanks for the propositions.

It is A LOT of works. So I pick only one things : 

> The per user access could be on the user page, with a challenge id in the url as an optional parameter that would add all the entries [... next text removed, too much work....]

I thought like you, and told me "So this request will take me just 2 hours if I go to the essential"


I tried a simple page. And then lot of questions / case appears.

Take https://www.vimgolf.com/challenges/5cf62aa56c09760009d6b2f3

And allow any click on user name to go to https://www.vimgolf.com/challenges/5cf62aa56c09760009d6b2f3/UserName

Which, as you said, should display every submitted solution : 

What if current_user are not connected ? 
- display the longuest solution (same as on a challenge, but then, people can 'cheat' by checking every users)
- do not display any solution (I prefere this one as a starter, simpler)

What if current_user has a keystroke > than UserName
- display the longuest solution (same as on a challenge, but then, people can 'cheat' by checking every users)
- do not display any solution (I prefere this one as a starter, simpler)

Where do I put the link to solutions per username ?

Should we communicate on improvement on this website to bring more people and having new feature done ?

What to display at the right column "Leaderboard (lowest score wins):" ?
- I m going for 'nothing' for this new page

Should we paginate this page ?
- I m going for 'no' as a beginning

For me the hardest part is the mongodb queries.

Thanks for your attention, I know where to start now, and we will have all the time to improve it :)

**Comment by filbranden** [comment]
This has been implemented.
